name: "XAU/USD Momentum Strategy"
strategy_type: "momentum"
parameters:
  fast_ma_period: 10  # Fast moving average
  slow_ma_period: 30  # Slow moving average
  momentum_period: 20  # Momentum calculation period
  threshold: 2.0  # Momentum threshold
  position_size: 0.15  # Position size
  stop_loss: 5.0  # Stop loss in USD
  take_profit: 4.0  # Take profit in USD
  min_volume: 0.1  # Minimum volume
  max_trades_per_hour: 30  # Moderate frequency
  volatility_threshold: 1.0  # Minimum volatility
  trend_strength: 0.6  # Minimum trend strength
