name: "XAU/USD Profitable Momentum Strategy"
strategy_type: "profitable_momentum"
parameters:
  fast_ma_period: 5  # Very fast MA for quick signals
  slow_ma_period: 15  # Slow MA for trend confirmation
  momentum_period: 10  # Momentum calculation period
  acceleration_threshold: 0.2  # Minimum acceleration
  volume_confirmation: true  # Require volume confirmation
  position_size: 0.03  # Smaller position size
  stop_loss: 0.8  # Tight stop loss
  take_profit: 1.2  # Realistic take profit
  max_trades_per_hour: 20  # Conservative rate limiting
  min_trend_strength: 0.1  # Minimum trend strength (reduced)
  volatility_filter: 0.05  # Maximum volatility threshold (reduced)
  rsi_filter: true  # Use RSI to avoid overbought/oversold
  rsi_period: 7  # Fast RSI for quick signals
